/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as PaymentPendingRouteImport } from './routes/payment-pending'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ShippingDeliveryRouteImport } from './routes/shipping-delivery'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPendingRoute = PaymentPendingRouteImport.update({
  id: '/payment-pending',
  path: '/payment-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingDeliveryRoute = ShippingDeliveryRouteImport.update({
  id: '/shipping-delivery',
  path: '/shipping-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-pending': typeof PaymentPendingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-pending': typeof PaymentPendingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-pending': typeof PaymentPendingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/dashboard'
    | '/features'
    | '/history'
    | '/integrations'
    | '/login'
    | '/payment-failed'
    | '/payment-pending'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-delivery'
    | '/signup'
    | '/support'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/dashboard'
    | '/features'
    | '/history'
    | '/integrations'
    | '/login'
    | '/payment-failed'
    | '/payment-pending'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-delivery'
    | '/signup'
    | '/support'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-docs'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/dashboard'
    | '/features'
    | '/history'
    | '/integrations'
    | '/login'
    | '/payment-failed'
    | '/payment-pending'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-delivery'
    | '/signup'
    | '/support'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  HistoryRoute: typeof HistoryRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentPendingRoute: typeof PaymentPendingRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingDeliveryRoute: typeof ShippingDeliveryRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-pending': {
      id: '/payment-pending'
      path: '/payment-pending'
      fullPath: '/payment-pending'
      preLoaderRoute: typeof PaymentPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-delivery': {
      id: '/shipping-delivery'
      path: '/shipping-delivery'
      fullPath: '/shipping-delivery'
      preLoaderRoute: typeof ShippingDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  HistoryRoute: HistoryRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentPendingRoute: PaymentPendingRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingDeliveryRoute: ShippingDeliveryRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
